---
    - name: Install and configure Wireguard. 
      hosts: wireguard
      become: true
      vars:
        wireguard_clients: 4
        private_network: '172.16.0'

      roles:
        - unbound
        - wireguard
