---
- name: Install and configure Wireguard. 
  hosts: all
  become: true
  vars:
    wireguard_clients: 10
    wireguard_port: 2408
    private_network: '172.16.0'

  roles:
    - unbound
    - wireguard
