---
- name: Install Unbound.
  package:
    name: "{{ unbound_package }}"
    state: present
  tags:
    - wg_init
    - dns
    - never

- name: Download the list of root DNS servers.
  get_url:
    url: https://www.internic.net/domain/named.cache
    dest: /var/lib/unbound/root.hints
    owner: unbound
    group: unbound
  tags:
    - wg_init
    - dns
    - never

- name: Check systemd-resolved config exist.
  stat:
    path: /etc/systemd/resolved.conf
  register: resolved_check
  tags:
    - wg_init
    - dns
    - never

- include_tasks: local-stub-resolver.yml
  when: resolved_check.stat.exists
  tags:
    - wg_init
    - dns
    - never

- name: Configure the system to use the local unbound DNS.
  lineinfile:
    path: /etc/resolv.conf
    regexp: '^nameserver'
    line: 'nameserver 127.0.0.1'
    create: yes
  when: not resolved_check.stat.exists
  tags:
    - wg_init
    - dns
    - never

- name: Generate Unbound config.
  template:
    src: unbound.conf.j2
    dest: /etc/unbound/unbound.conf
  notify: restart {{ unbound_service }}
  tags:
    - wg_init
    - dns
    - never

- name: Enable and start Unbound service.
  systemd:
    name: "{{ unbound_service }}"
    enabled: yes
    state: started
  tags:
    - wg_init
    - dns
    - never

