---
- include_tasks: wg_peer_add.yml
  tags:
    - wg_peer_add

- include_tasks: wg_peer_rm.yml
  tags:
    - wg_peer_rm

- name: Install Wireguard.
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - "{{ wireguard_package }}"
    - iptables
  tags:
    - wg_init
    - never

- name: Allowing traffic forwarding ipv4.
  sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    state: present
    reload: yes
  tags:
    - wg_init
    - never

- name: Get interface name.
  shell: ip -o -4 route show to default | awk '{print $5}'
  register: interface
  tags:
    - wg_init
    - never

- name: Generate private and public keys.
  shell: wg genkey | tee {{ wireguard_config_files_path }}/private{{ item }}.key | wg pubkey | tee {{ wireguard_config_files_path }}/public{{ item }}.key
  with_sequence: start=0 end={{ wireguard_clients }}
  tags:
    - wg_init
    - never

- name: Register private key file contents.
  shell: cat {{ wireguard_config_files_path }}/private{{ item }}.key
  register: private_key_files
  with_sequence: start=0 end={{ wireguard_clients }}
  tags:
    - wg_init
    - never

- name: Register public key file contents.
  shell: cat {{ wireguard_config_files_path }}/public{{ item }}.key
  register: public_key_files
  with_sequence: start=0 end={{ wireguard_clients }}
  tags:
    - wg_init
    - never

- name: Stop Wireguard service.
  systemd:
    name: "{{ wireguard_service }}"
    state: stopped
  tags:
    - wg_init
    - never

- name: Copy Wireguard configuration.
  template:
    src: wg0.conf.j2
    dest: "{{ wireguard_config_files_path }}/wg0.conf"
    owner: root
    group: root
    mode: 0600
  tags:
    - wg_init
    - never

- name: Ensure Wireguard is started and enabled at boot.
  systemd:
    name: "{{ wireguard_service }}"
    enabled: yes
    state: started
  tags:
    - wg_init
    - never

- name: Register the clients on the Wireguard server.
  shell: wg set wg0 peer {{ public_key_files.results[item|int].stdout }} allowed-ips {{ private_network }}.{{item|int + 1}}/32
  with_sequence: start=1 end={{ wireguard_clients }}
  notify: restart {{ wireguard_service }}
  tags:
    - wg_init
    - never

- name: Generate client configs and saving to localhost.
  template:
    src: wg0-client.conf.j2
    dest: "wg-profiles/wg0-client{{ item }}.conf"
  with_sequence: start=1 end={{ wireguard_clients }}
  delegate_to: localhost
  become: false
  tags:
    - wg_init
    - never
